# Initialize database from schema.sql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/company?useSSL=false&serverTimezone=Europe/Warsaw
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: admin
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
